version: '3.3'
services:
  broker:
    image: rabbitmq:3-management-alpine
    container_name: 'broker'
    hostname: 'broker'
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq/
    #   - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - default

networks:
  default:
    driver: bridge